baseURL: https://co-analysis.github.io/coding-guide/
languageCode: en-gb
title: Analytical Coding Guide
theme: govukhugo
publishDir: docs
canonifyurls: true

pygmentsUseClasses: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: github
    tabWidth: 2

params:
  govuk: false
  logotext: ACG
  product: Analytical Coding Guide
  phase: alpha
  feedbackurl: https://github.com/co-analysis/coding-guide/issues/
  accessibility: accessibility.md
  cookies: cookies.md
  builtby: "Cabinet Office Analysis & Insight"
  builtbyurl: https://www.github.com/co-analysis