# Analytical Coding Guide

::: {.lead-para}
This site provides the Cabinet Office Analysis & Insight team's guide for coding in analytical projects.
:::

The purpose of this guide is to provide simple advice about how to use code in our analysis. It is broken down into three sections: **workflow**, **style** and **output**. This site is a 'living document' that will evolve as our approach develops/changes. While the guide is intended to be language independent, given our practice examples are more likely to be based on using [R](https://www.r-project.org) or [R Studio](https://www.rstudio.com). Our approach to coding and analysis is particularly influenced by the [Tidyverse](https://tidyverse.org).

This guide isn't designed to provide a rulebook of 'hard' standards that must be followed, rather it provides advice and general guidelines to using code in analytical projects. There are many [other guides and resources](resources.html) developed by others, which provide more detailed information and have influenced this guide to more o. Each person and team also have their own individual style and perferences - this guide is designed to provide some common building blocks so that it is easier for our analysts to work together when coding.


## Workflow
Our [workflow](workflow.html) guidelines set out how you should structure and manage code in an analytical project.

1. Project-based working
1. Scripting
1. Functional programming
1. Dependency management
1. Version control (git)
1. Documentation
1. QA and code review

## Style
Our [style](style.html) guidelines set out how to write code for a project.

1. Naming conventions
1. Code Flow
1. Syntax
1. Pipe
1. Comments and documentation
1. Error messages

## Output
Our [output](output.html) guidelines set out some principles for presenting results.

1. Tables
2. Graphs
3. Slide decks
4. Publishing

---

::: {.small-para}
This site was built using [govdown](https://ukgovdatascience.github.io/govdown/).

[Sitemap](sitemap.html)
:::
