---
output: 
  govdown::govdown_document:
    page_title: "ACG - Workflow"
---

::: {.breadcrumbs}
* [ACG](index.html)
* Workflow
:::

# Workflow guidelines

::: {.lead-para}
Our workflow guidelines set out how you should structure and manage code in an analytical project.
:::

::: {.warning}
In development: this is unfinished and still being writen, links may not work.
:::

#### Table of contents
1. [Project based working](#project-based-working)
1. [Scripting](#scripting)
1. [Functional programming](#functional-programming)
1. [Dependency management](#dependency-management)
1. [Version control](#version-control-git)
1. [Documentation](#documentation)
1. [QA and code review](#qa-and-code-review)

### Project based working

Analytical projects generally, but especially those using code, should be managed as a **project**.

A project is a discrete piece of work/analysis that is self-contained and can be run on its own. It may rely on other work, data or specific packages (see dependency management), but assuming you have access to the other work, data or packages you ought to be able to run this code.

Projects should be contained in separate, distinct, and well named, folders. Unless using version control, these project folders should be stored on the shared drive (the `S` drive, or `SCSPS`). The shared drive or GitHub repository should be the cannonical version of the code.

RStudio has project-based working built into the IDE, read the explainer on [RStudio projects](workflow-rsprojects.html).

::: {.small-para}
[\^ Back to table of contents](#table-of-contents)
:::

### Scripting

A file containing code is called a script, the process of creating a script is called **scripting**.

To help improve the readability of your code and enable others to more easily use and review your project you should avoid the 'kitchen sink' approach to scripting - that is, writing all your code in one single file. Instead break up your code into discrete chunks and save each of those as separate scripts. When using multiple scripts, do not put a link to `script1.file` at the start of `script2.file` instead use a master script that calls the separate scripts.

There is no particular convention on how to chunk up your code, but some good rules of thumb are:

* Define and write functions in a separate script from function calls - this makes it much easier to load functions.
* Think about the stages of your analysis (e.g. cleaning/processing, analysis/modelling, outputs).
* Is there a simple name (beside the project name) that can easily explain the contents of the script and what it does (e.g. `data_merging.file`).
* If your code was a book, think about each script as a separate chapter.

::: {.small-para}
[\^ Back to table of contents](#table-of-contents)
:::

### Functional programming

Functions are code that you can call and use again - e.g. `mean(1, 2, 3, 4)` gives the average (mean) of the numbers 1, 2, 3 and 4 or in this case 2.5.

Functions are generally provided by packages or libraries, but can also be written by yourself - are you even a coder if you've not written a function.

**Functional programming** in analysis is about thinking about your work as a series of functions that manipulate input(s) to produce output(s). Breaking your work down into functions makes it easier to write and develop your project, it also makes it easier for other people to review and understand your work.

Read the explainer on using [functional programming](workflow-programming.html) for analysis.

::: {.small-para}
[\^ Back to table of contents](#table-of-contents)
:::

### Dependency management

Ensuring reproducible research and analysis requires not only code, but ensuring that you are using the same/compatible versions of extensions (packages/libraries) - this is called **dependency management**.

It is important to ensure that you document which versions of the base language and extensions are being used. It can also be useful to store your system information.

Read the explainer on [dependency management](workflow-dependencies.html).

::: {.small-para}
[\^ Back to table of contents](#table-of-contents)
:::

### Version control (git)

Just as we use version control when writing documents, we should use **version control** when writing code. Rather than saving multiple versions of files (e.g. `code-draft1.file`, `code-draft2.file`, `code-final.file` and, `code-final-FINAL.file`) we use [git](https://git-scm.com/) to manage versioning. Think of it as "track changes" for code.

Read the explainer on using [git and github](workflow-git.html).

::: {.small-para}
[\^ Back to table of contents](#table-of-contents)
:::

### Documentation

You must **document** your code. We rarely do analysis on our own, and there will definitely be circumstances when someone else needs to use it: you're on leave or off sick, or you've moved on to another team. Documentation ensures that it is easy to follow what the code you write does, and is essential if you are collaborating on a project with others. It can also be really helpful to yourself, when you come to repeat a piece of work having it documented will make it a lot easier to 

Read the explainer on [documentation](workflow-documentation.html).

::: {.small-para}
[\^ Back to table of contents](#table-of-contents)
:::

### QA and code review

Quality assurance and code review are important parts of the project lifecycle - and an example of peer review. Within this guide we use **quality assurance** (or 'QA') to refer to verifying that the analysis is correct - are we using the right methods, does it give the numbers we expect, etc. While **code review** is about checking whether the code is written well and conforms to our core standards.

Read the explainer on [QA and code review](workflow-qa-code.html) in analytical projects.

::: {.small-para}
[\^ Back to table of contents](#table-of-contents)
:::
